services:
  postgres:
    image: postgres:15-alpine
    container_name: pinga_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pxel0581
      POSTGRES_DB: CODE_PINGA
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgres://postgres:pxel0581@postgres:5432/CODE_PINGA
    container_name: pinga_backend
    environment:
      - DATABASE_URL=postgres://postgres:pxel0581@postgres:5432/CODE_PINGA
      - JWT_SECRET=Devil of the Paradise
      - JWT_EXPIRES_IN=1d
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pinga_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
